# Generated by Django 5.0.2 on 2024-05-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_customuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
